Added Design Guidelines
CheshtaK/bookface pull request #15
Opened 2020-06-20 16:46 UTC by ishandeveloper

### Description
Added design guidelines, mockups, color palette and other assets for the design.

Closes #12 

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged
- [x] My changes generate no new warnings
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning)

2020-06-21 13:37 UTC, CheshtaK commented
LGTM @ishandeveloper . Open a new issue for the Chat page so that we can work on it later.

2020-06-21 13:37 UTC, CheshtaK approved these changes

2020-06-21 15:02 UTC, ishandeveloper commented
Okay @CheshtaK created a new issue in #16 .

@himanshusharma89 can you please take a look and merge this PR?

2020-06-21 15:03 UTC, ishandeveloper commented
#### Also, can you assign #4 to me now?

2020-06-21 16:20 UTC, CheshtaK commented
@himanshusharma89 We'll keep this PR open for now. There are a few things to be discussed. Will ping on Slack in a couple of days.

2020-06-28 09:26 UTC, CheshtaK requested changes

2020-06-28 09:26 UTC, CheshtaK commented on DESIGN.md
> +1. Bring out that inner artist of yours, and show your creativity! 😄
Could you correct the numbering here?

2020-06-29 20:54 UTC, ishandeveloper commented on DESIGN.md
> +1. Bring out that inner artist of yours, and show your creativity! 😄
I actually added that intentionally, so that Github's markdown would kick in and automatically add the numbering 😅
Still I have made the requested changes. 😃

2020-06-30 18:09 UTC, merged