Splashscreen configured
CheshtaK/bookface pull request #27
Opened 2020-07-01 12:24 UTC by abhinavsri360

### Description
Configured the Splash screen as per Design guidelines. The screenshot is provided below.

Fixes # [ISSUE]
Closes #25 
### How Has This Been Tested?
via running on my android device

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged
- [x] My changes generate no new warnings

Screenshot::
![Screenshot_20200701-173819](https://user-images.githubusercontent.com/44001310/86243060-50647880-bbc3-11ea-91fa-7ce43994e678.png)

2020-07-02 12:48 UTC, abhinavsri360 commented
@himanshusharma89 @CheshtaK Animations added and this page is up and running.

2020-07-02 16:05 UTC, CheshtaK requested changes
Could you also provide a gif? The code looks good but I can't test it right now. A gif would be helpful.

2020-07-02 16:05 UTC, CheshtaK commented on lib/constants/strings.dart
> +  static const String app_name = 'Bookface';
@abhinavsri360 Let's keep this as before. It's a style we're using for the app name.

2020-07-02 16:05 UTC, CheshtaK commented on lib/constants/strings.dart
> +  static const String welcome = 'Welcome to Bookface';
Same goes for this. We could discuss more about it if you feel differently. Feel free to ping me on Slack!

2020-07-02 18:54 UTC, abhinavsri360 commented
@CheshtaK Here's the gif to the animation.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44001310/86398554-6bb6ad00-bcc3-11ea-91c7-73e4432fc12f.gif)

2020-07-02 18:57 UTC, himanshusharma89 commented
Looks good to me, @CheshtaK

2020-07-03 05:03 UTC, CheshtaK approved these changes
LGTM

2020-07-03 05:03 UTC, merged